const express = require('express');
const r = express.Router();
const c = require('../controllers/dealerController');
const { protect, authorize } = require('../middleware/auth');
const managers = ['admin', 'nsm', 'rsm', 'asm', 'se', 'so'];
r.use(protect);
r.get('/',     c.getAll);
r.get('/:id/collections', c.collections);
r.get('/:id/invoices',    c.invoices);
r.get('/:id/ledger',      c.ledger);
r.get('/:id',  c.getOne);
r.post('/',    authorize('admin', 'nsm', 'rsm', 'asm', 'se'), c.create);
r.put('/:id',  authorize('admin', 'nsm', 'rsm', 'asm', 'se'), c.update);
r.delete('/:id', authorize('admin', 'nsm'), c.remove);
r.put('/:id/assign-so', authorize('admin', 'nsm', 'rsm', 'asm', 'se'), c.assignSO);
r.put('/:id/link-user', authorize('admin', 'nsm'), c.linkUser);
module.exports = r;
