const express = require('express');
const r = express.Router();
const c = require('../controllers/orderController');
const { protect, authorize } = require('../middleware/auth');
r.use(protect);
r.get('/',                  c.getAll);
r.get('/:id',               c.getOne);
r.post('/',                 authorize('admin', 'nsm', 'rsm', 'asm', 'se', 'so'), c.create);
r.put('/:id',               authorize('admin', 'nsm', 'rsm', 'asm', 'se', 'so'), c.update);
r.patch('/:id/status',      authorize('admin', 'nsm', 'rsm', 'asm'), c.updateStatus);
r.patch('/:id/review',      authorize('admin', 'nsm', 'rsm', 'asm'), c.reviewOrder);
r.delete('/:id',            authorize('admin', 'nsm'), c.remove);
module.exports = r;
