const express = require('express');
const r = express.Router();
const c = require('../controllers/productController');
const { protect } = require('../middleware/auth');
r.use(protect);
r.get('/',     c.getAll);
r.get('/:id',  c.getOne);
r.post('/',    c.create);
r.put('/:id',  c.update);
r.delete('/:id', c.remove);
module.exports = r;
