const express = require('express');
const r = express.Router();
const c = require('../controllers/userController');
const { protect, authorize } = require('../middleware/auth');
r.use(protect);
r.get('/',                    authorize('nsm','rsm','asm','se','admin'), c.getAll);
r.get('/subordinates',        c.getSubordinates);
r.get('/:id',                 c.getOne);
r.post('/',                   authorize('nsm','rsm','asm','admin'), c.create);
r.put('/:id',                 authorize('nsm','rsm','asm','admin'), c.update);
r.patch('/:id/status',        authorize('nsm','rsm','asm','admin'), c.toggleStatus);
r.put('/:id/reset-password',  authorize('nsm','admin'), c.resetPassword);
r.delete('/:id',              authorize('nsm','admin'), c.remove);
module.exports = r;
